#ifndef _DEFINES_H_
#define ID_SPRITE_HERO 0
#define ID_SPRITE_KNIGHT 1

#define ID_SPLIST_HERO 0

#define ID_TITLEMAP_MAP 0

#define ID_BUTTON_PLAY 0
#define ID_BUTTON_RESUME 1
#define ID_BUTTON_HOME 2

#define ID_FONT_MARKERFELT 0
#define ID_FONT_ARIAL 1

#define ID_SOUND_SONTUNG 0

#define TEAM_BLUE 0
#define TEAM_RED 1
#define RANGER_ATTACK 300

#define TAG_ACTION_WALK 0
#define TAG_ACTION_ATTACK 1

#endif
